var _unk_d_o_p_8h =
[
    [ "KDopSIMD", "d1/d27/struct_k_dop_s_i_m_d.html", "d1/d27/struct_k_dop_s_i_m_d" ],
    [ "FkDOPCollisionTriangle< BOUND_TYPE >", "d1/d0c/struct_fk_d_o_p_collision_triangle.html", "d1/d0c/struct_fk_d_o_p_collision_triangle" ],
    [ "FkDOPBuildCollisionTriangle< KDOP_IDX_TYPE >", "da/d47/struct_fk_d_o_p_build_collision_triangle.html", "da/d47/struct_fk_d_o_p_build_collision_triangle" ],
    [ "TkDOPPhysicalMaterialCheck< COLL_DATA_PROVIDER, KDOP_IDX_TYPE >", "d2/d86/struct_tk_d_o_p_physical_material_check.html", "d2/d86/struct_tk_d_o_p_physical_material_check" ],
    [ "FkDOPPlanes", "de/d0c/struct_fk_d_o_p_planes.html", "de/d0c/struct_fk_d_o_p_planes" ],
    [ "FLineCollisionInfo", "d8/d1c/struct_f_line_collision_info.html", "d8/d1c/struct_f_line_collision_info" ],
    [ "TkDOP< COLL_DATA_PROVIDER, KDOP_IDX_TYPE >", "d8/d6f/struct_tk_d_o_p.html", "d8/d6f/struct_tk_d_o_p" ],
    [ "TkDOPNode< COLL_DATA_PROVIDER, KDOP_IDX_TYPE >", "d5/dd0/struct_tk_d_o_p_node.html", "d5/dd0/struct_tk_d_o_p_node" ],
    [ "TkDOPTree< COLL_DATA_PROVIDER, KDOP_IDX_TYPE >", "de/db3/struct_tk_d_o_p_tree.html", "de/db3/struct_tk_d_o_p_tree" ],
    [ "TkDOPCompact< COLL_DATA_PROVIDER, KDOP_IDX_TYPE >", "da/d1b/struct_tk_d_o_p_compact.html", "da/d1b/struct_tk_d_o_p_compact" ],
    [ "TkDOPNodeCompact< COLL_DATA_PROVIDER, KDOP_IDX_TYPE >", "d6/d81/struct_tk_d_o_p_node_compact.html", "d6/d81/struct_tk_d_o_p_node_compact" ],
    [ "TkDOPNodeCompact< COLL_DATA_PROVIDER, KDOP_IDX_TYPE >::FTraversalData", "d5/db8/struct_tk_d_o_p_node_compact_1_1_f_traversal_data.html", "d5/db8/struct_tk_d_o_p_node_compact_1_1_f_traversal_data" ],
    [ "TkDOPTreeCompact< COLL_DATA_PROVIDER, KDOP_IDX_TYPE >", "d7/d5d/struct_tk_d_o_p_tree_compact.html", "d7/d5d/struct_tk_d_o_p_tree_compact" ],
    [ "TkDOPCollisionCheck< COLL_DATA_PROVIDER, KDOP_IDX_TYPE, TREE_TYPE >", "d1/d79/struct_tk_d_o_p_collision_check.html", "d1/d79/struct_tk_d_o_p_collision_check" ],
    [ "TkDOPLineCollisionCheck< COLL_DATA_PROVIDER, KDOP_IDX_TYPE, TREE_TYPE >", "d4/db0/struct_tk_d_o_p_line_collision_check.html", "d4/db0/struct_tk_d_o_p_line_collision_check" ],
    [ "TkDOPBoxCollisionCheck< COLL_DATA_PROVIDER, KDOP_IDX_TYPE, TREE_TYPE >", "d7/d79/struct_tk_d_o_p_box_collision_check.html", "d7/d79/struct_tk_d_o_p_box_collision_check" ],
    [ "TkDOPPointCollisionCheck< COLL_DATA_PROVIDER, KDOP_IDX_TYPE, TREE_TYPE >", "dd/d41/struct_tk_d_o_p_point_collision_check.html", "dd/d41/struct_tk_d_o_p_point_collision_check" ],
    [ "TkDOPSphereQuery< COLL_DATA_PROVIDER, KDOP_IDX_TYPE, TREE_TYPE >", "d4/d47/struct_tk_d_o_p_sphere_query.html", "d4/d47/struct_tk_d_o_p_sphere_query" ],
    [ "TkDOPAABBQuery< COLL_DATA_PROVIDER, KDOP_IDX_TYPE, TREE_TYPE >", "d0/dd1/struct_tk_d_o_p_a_a_b_b_query.html", "d0/dd1/struct_tk_d_o_p_a_a_b_b_query" ],
    [ "TkDOPFrustumQuery< COLL_DATA_PROVIDER, KDOP_IDX_TYPE, TREE_TYPE >", "d3/d29/struct_tk_d_o_p_frustum_query.html", "d3/d29/struct_tk_d_o_p_frustum_query" ],
    [ "TkDOPFrustumQuery< COLL_DATA_PROVIDER, KDOP_IDX_TYPE, TREE_TYPE >::FTriangleRun", "db/dde/struct_tk_d_o_p_frustum_query_1_1_f_triangle_run.html", "db/dde/struct_tk_d_o_p_frustum_query_1_1_f_triangle_run" ],
    [ "COMPACT_KDOP_SIMD_DECOMPRESSION", "d9/df8/_unk_d_o_p_8h.html#a9b434b021f1a7c8aa1d46346630a2932", null ],
    [ "FUDGE_SIZE", "d9/df8/_unk_d_o_p_8h.html#af1beae2ca028e7f06783f284814f19ba", null ],
    [ "KDOP_INLINE", "d9/df8/_unk_d_o_p_8h.html#af39d20b4193258d1052594b8671ae781", null ],
    [ "LINE_TRIANGLE_EPSILON", "d9/df8/_unk_d_o_p_8h.html#a86657353273299e216a663c8694bb5dd", null ],
    [ "MAX_FLT", "d9/df8/_unk_d_o_p_8h.html#a58ce70c44358a600c06e31eb3be28b61", null ],
    [ "MAX_TRIS_PER_LEAF", "d9/df8/_unk_d_o_p_8h.html#afaad9924e8f7ac6345c770cc46314088", null ],
    [ "MAX_TRIS_PER_LEAF_COMPACT", "d9/df8/_unk_d_o_p_8h.html#af6da271455de282546f0de130593f1f0", null ],
    [ "NUM_PAD_NODES", "d9/df8/_unk_d_o_p_8h.html#ace1834e0216a067b1a02bad87054a37c", null ],
    [ "NUM_PLANES", "d9/df8/_unk_d_o_p_8h.html#a015f94555ae101091453e7bbea527259", null ],
    [ "PARALLEL_LINE_KDOP_EPSILON", "d9/df8/_unk_d_o_p_8h.html#ab1f396a31f17f20f54efe443a9ab83a7", null ],
    [ "TEST_COMPACT_KDOP", "d9/df8/_unk_d_o_p_8h.html#afdb1aaea1dae2e0bec789dbb6331593b", null ],
    [ "TEST_COMPACT_KDOP_SLOW", "d9/df8/_unk_d_o_p_8h.html#abb6504219abee6201621592e1fd9a787", null ]
];