var _game_stats_database_types_8h =
[
    [ "FGameSessionEntryRemote", "d8/da9/struct_f_game_session_entry_remote.html", "d8/da9/struct_f_game_session_entry_remote" ],
    [ "FGameStatsRemoteDB", "d9/d5d/struct_f_game_stats_remote_d_b.html", "d9/d5d/struct_f_game_stats_remote_d_b" ],
    [ "LocationEntry", "d4/d2a/class_location_entry.html", "d4/d2a/class_location_entry" ],
    [ "GameStringEntry", "d8/def/class_game_string_entry.html", "d8/def/class_game_string_entry" ],
    [ "GameIntEntry", "d3/dcf/class_game_int_entry.html", "d3/dcf/class_game_int_entry" ],
    [ "GameFloatEntry", "de/d06/class_game_float_entry.html", "de/d06/class_game_float_entry" ],
    [ "GamePositionEntry", "df/d09/class_game_position_entry.html", "df/d09/class_game_position_entry" ],
    [ "TeamEntry", "d4/d2f/class_team_entry.html", "d4/d2f/class_team_entry" ],
    [ "TeamIntEntry", "dc/d3b/class_team_int_entry.html", "dc/d3b/class_team_int_entry" ],
    [ "TeamFloatEntry", "dc/d48/class_team_float_entry.html", "dc/d48/class_team_float_entry" ],
    [ "TeamStringEntry", "d3/de3/class_team_string_entry.html", "d3/de3/class_team_string_entry" ],
    [ "PlayerEntry", "d2/da2/class_player_entry.html", "d2/da2/class_player_entry" ],
    [ "PlayerStringEntry", "de/db8/class_player_string_entry.html", "de/db8/class_player_string_entry" ],
    [ "PlayerIntEntry", "dd/db4/class_player_int_entry.html", "dd/db4/class_player_int_entry" ],
    [ "PlayerFloatEntry", "d3/d29/class_player_float_entry.html", "d3/d29/class_player_float_entry" ],
    [ "PlayerLoginEntry", "de/d79/class_player_login_entry.html", "de/d79/class_player_login_entry" ],
    [ "PlayerSpawnEntry", "de/da2/class_player_spawn_entry.html", "de/da2/class_player_spawn_entry" ],
    [ "PlayerKillDeathEntry", "de/dcd/class_player_kill_death_entry.html", "de/dcd/class_player_kill_death_entry" ],
    [ "PlayerPlayerEntry", "d1/dfa/class_player_player_entry.html", "d1/dfa/class_player_player_entry" ],
    [ "WeaponEntry", "d8/d32/class_weapon_entry.html", "d8/d32/class_weapon_entry" ],
    [ "DamageEntry", "d0/d61/class_damage_entry.html", "d0/d61/class_damage_entry" ],
    [ "ProjectileIntEntry", "d8/d09/class_projectile_int_entry.html", "d8/d09/class_projectile_int_entry" ],
    [ "GenericParamListEntry", "dd/daf/class_generic_param_list_entry.html", "dd/daf/class_generic_param_list_entry" ],
    [ "__GAMESTATSDATABASETYPES_H__", "df/d29/_game_stats_database_types_8h.html#a516996309976c7f79081601781089a66", null ],
    [ "ParseSessionID", "df/d29/_game_stats_database_types_8h.html#a3b65f2e3844ba07bb057c305e88ccbec", null ]
];