var struct_online_playlist_manager__event_on_playlist_population_data_updated___parms =
[
    [ "OnlinePlaylistManager_eventOnPlaylistPopulationDataUpdated_Parms", "d6/dec/struct_online_playlist_manager__event_on_playlist_population_data_updated___parms.html#a73c417616c1e851cf1458ce4fa43e5fa", null ]
];